/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mail.glb 
*/

import React from 'react'
import { useGLTF, Text } from '@react-three/drei'
import * as THREE from 'three'

export function Mail (props) {
  const { nodes, materials } = useGLTF('/models/mail.glb')
  const { nodes: planeNodes, materials: planeMaterials } = useGLTF(
    '/models/paperplane.glb'
  )

  const redMaterial = new THREE.MeshPhongMaterial({ color: '#CB0404' })
  return (
    <group {...props} dispose={null}>
      <group position={[4, 30, 8]} scale={7} rotation={[Math.PI / 1.1, 0, 1]}>
        <group position={[1, 2, 4]} rotation={[Math.PI / 1, 0, 1]}>
          <mesh
            geometry={nodes.open_mail_open_mail_0_1.geometry}
            material={materials.new_colorOS}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.open_mail_open_mail_0_2.geometry}
            material={materials.open_mail}
            castShadow
            receiveShadow
          />
        </group>
        <group position={[2, -1, 0]} rotation={[Math.PI / 1.1, 0, 1]}>
          <mesh
            geometry={planeNodes.Object_5.geometry}
            material={redMaterial}
            position={[-1.5, 1, -5]}
            rotation={[Math.PI / 2, 0, 0.25]}
            scale={7}
          />
        </group>

        <Text
          position={[4, 6, -4]}
          fontSize={3}
          color='white'
          anchorX='center'
          anchorY='middle'
          rotation={[Math.PI / 1, 0, 1]}
          castShadow
          receiveShadow
        >
          LET'S CONNECT!
        </Text>
      </group>
      <Text
        position={[85, 2, 45]} // ปรับตำแหน่งให้ต่อท้าย
        fontSize={35}
        color='yellow'
        rotation={[Math.PI / -10, 0, 6.5]}
        castShadow
        receiveShadow
      >
        🚀
      </Text>
    </group>
  )
}

useGLTF.preload('/models/mail.glb')
useGLTF.preload('/models/paperplane.glb')
