/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 paperplane.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/paperplane.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_5.geometry} material={materials['glossy_putih.001']} position={[0, 3, 6]} rotation={[Math.PI / 2, 0, 0]} scale={0.843} />
      </group>
    </group>
  )
}

useGLTF.preload('/paperplane.glb')
